### PR TITLE
Add X11 display support

### PR DESCRIPTION
**Pull request by nicolube**
Adds X11 window support.
Also auto sets DISPLAY to the DISPLAY of host.

### CODE REVIEW

**Comment by nicolube** [comment]
CI does fail, the cause of that is that Debian stretch is missing repos, I recommend to remove it.

**Comment by ooxi** [comment]
Not all systems running mini-cross do run X11, nevertheless I think X11 support should be merged.

**Comment by nicolube** [comment]
@ooxi Bump.
You tould me u would merge it, but this request is still open.

> Not all systems running mini-cross do run X11, nevertheless I think X11 support should be merged.

Event if a system does not support x11, docker will just reate the path to the X11 dir and the DISPLAY should just be "".
So it will not break it.

**Comment by ooxi** [comment]
Thank you!

**Pull request merged**
